// <auto-generated />
using System;
using Gym.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112020122_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym.Domain.Entities.BodyMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("Biceps")
                        .HasColumnType("decimal")
                        .HasColumnName("biceps");

                    b.Property<decimal?>("BodyFat")
                        .HasColumnType("decimal")
                        .HasColumnName("body_fat");

                    b.Property<decimal?>("Calves")
                        .HasColumnType("decimal")
                        .HasColumnName("calves");

                    b.Property<decimal?>("Chest")
                        .HasColumnType("decimal")
                        .HasColumnName("chest");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 11, 12, 2, 1, 22, 485, DateTimeKind.Utc).AddTicks(3777))
                        .HasColumnName("created-at");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal")
                        .HasColumnName("height");

                    b.Property<decimal?>("Hips")
                        .HasColumnType("decimal")
                        .HasColumnName("hips");

                    b.Property<DateOnly?>("MeasurementDate")
                        .HasColumnType("date")
                        .HasColumnName("measurement_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Thighs")
                        .HasColumnType("decimal")
                        .HasColumnName("thighs");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 11, 12, 2, 1, 22, 487, DateTimeKind.Utc).AddTicks(664))
                        .HasColumnName("updated-at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("Waist")
                        .HasColumnType("decimal")
                        .HasColumnName("waist");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("body_measurements", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 11, 12, 2, 1, 22, 492, DateTimeKind.Utc).AddTicks(9168))
                        .HasColumnName("created-at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2025, 11, 12, 2, 1, 22, 492, DateTimeKind.Utc).AddTicks(9427))
                        .HasColumnName("updated-at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Gym.Domain.Entities.BodyMeasurement", b =>
                {
                    b.HasOne("Gym.Domain.Entities.User", "User")
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gym.Domain.Entities.User", b =>
                {
                    b.Navigation("BodyMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
